/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhakui_ishare_NativeUtils */

#ifndef _Included_com_zhakui_ishare_NativeUtils
#define _Included_com_zhakui_ishare_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhakui_ishare_NativeUtils
 * Method:    getname
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zhakui_ishare_NativeUtils_getname
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
